### PR TITLE
Include u-boot and dockerfile

### PR DESCRIPTION
**Pull request by Ham22**

### CODE REVIEW

**Comment by nikhil-zinjurde-imgtec** [comment]
test with jenkins - dev

**Comment by nikhil-zinjurde-imgtec** [comment]
@Ham22 do you intend to just add source package for u-boot or also have it built every time you make a Ci40 image?

**Comment by Ham22** [comment]
For now its just to get the source checked out with the rest of the packages.

**Comment by nikhil-zinjurde-imgtec** [comment]
Approved & verified

**Pull request merged**
