### PR TITLE
Update AWALWM2M to 0.2.2

### PR DESCRIPTION
**Pull request by abhijit-mahajani-imgtec**
Signed-off-by: Abhijit Mahajani <Abhijit.Mahajani@imgtec.com>

### CODE REVIEW

**Comment by nikhil-zinjurde-imgtec** [comment]
test with jenkins - dev

**Comment by nikhil-zinjurde-imgtec** [comment]
test with jenkins - dev

**Comment by nikhil-zinjurde-imgtec** [comment]
test with jenkins - dev

**Comment by nikhil-zinjurde-imgtec** [comment]
test with jenkins - dev

**Comment by manohar-narkhede-imgtec** [comment]
compilation is failing with 0.2.2.

**Comment by abhijit-mahajani-imgtec** [comment]
Sorry it should be 0.2.1

**Pull request closed without merging**
